# Generated by Django 2.2 on 2019-12-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blk_app', '0002_auto_20191220_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.CharField(default='duane', max_length=60),
            preserve_default=False,
        ),
    ]
